version: '3'
services:
  redis-server:
    image: redis
    container_name: redis-server

  hello-api:
    build:
      context: .  # current directory
      dockerfile: Dockerfile.dev
    container_name: hello-api
    image: hello-api-build
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    depends_on:
      - redis-server

