version: '3'
services:
  redis-server:
    image: redis

  hello-api:
    build:
      context: .  # current directory
      dockerfile: Dockerfile.dev
    ports:
      - '80:80'
    volumes:
      - ./:/app
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    depends_on:
      - redis-server
