sudo: required
services:
  - docker

before_install:
  - cd production-grade-workflow
  - docker-compose -f docker-compose.yaml -f docker-compose.dev.yaml up --build -d
  - docker-compose ps

script:
  - docker exec -it hello-api-test pytest --ignore=tests/ --cov=app tests/ --cov-config=.coveragerc

after_success:
    - codecov